[package]
name = "arcoracle-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
rig = "0.6.0"
rig-lancedb = "0.1"
tokio = { version = "1.0", features = ["full"] }
solana-sdk = "1.18"
serde_json = "1.0"
dotenv = "0.15"

[dev-dependencies]
